apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
spec:
  selector:
    app: {{ .Values.appName }}-backend
  ports:
    - port: 80
      targetPort: {{ .Values.backend.port }}
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
spec:
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.service.type }}
