version: "3.9"

services:
  todo-db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"

  todo-backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DB_HOST: todo-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - todo-db

  todo-frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - todo-backend

volumes:
  todo_pg_data:
