version: "3.9"

services:
  blog-db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - blog_pg_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT:-5433}:5432"

  blog-backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DB_HOST: blog-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 8000
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - blog-db

  blog-frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    depends_on:
      - blog-backend

volumes:
  blog_pg_data:
